name: Deploy RG Balancer

on:
  workflow_dispatch:

env: # 👈 global env
  APP_NAME: resolute-games
  BAL_REGION: ewr
  RELAY_MATRIX: |
  [
    {"region": "ewr", "prefix": "ewr-1"}
  ]

jobs:
  # -------------------
  # Balancer (single region, no env overrides)
  # -------------------
  balancer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Balancer
        working-directory: PurrBalancer
        run: |
          flyctl deploy --remote-only \
            --app $APP_NAME \
            --primary-region $BAL_REGION
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  # -------------------
  # Relays (matrix deploy)
  # -------------------
  deploy:
    runs-on: ubuntu-latest
    needs: balancer
    strategy:
      matrix:
        include: ${{ fromJson(env.RELAY_MATRIX) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Relay
        working-directory: PurrLay
        run: |
          flyctl deploy --remote-only --strategy immediate \
            --app "${APP_NAME}-${{ matrix.prefix }}" \
            --primary-region ${{ matrix.region }} \
            --env BALANCER_URL=${{ secrets.BALANCER_RG_URL }} \
            --env HOST_DOMAIN=${{ secrets.HOST_RG_DOMAIN }} \
            --env HOST_REGION=${{ matrix.prefix }} \
            --env HOST_SSL="true"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
