name: rebuild-purr-balancer-br

on:
  push:
    paths: ['PurrLay/**']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 195.35.42.5
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Define variables
            SERVICE_NAME="PurrLay"
            DOMAIN="br.purrlay.riten.dev"
            REPO_DIR="PurrRelay"
            CERT_DIR="/etc/letsencrypt/live/$DOMAIN"
            PFX_CERT="$CERT_DIR/fullchain.pfx"
            CERT_PASSWORD="YourSecurePasswordHerePurrLayBR"

            # Update and install dependencies
            apt-get update
            apt-get install -y dotnet-sdk-8.0 certbot openssl

            # Restart Certbot timer to ensure renewal works
            systemctl restart certbot.timer
            
            # Obtain a Let's Encrypt SSL certificate
            if [ ! -d "$CERT_DIR" ]; then
              echo "Generating Let's Encrypt certificate..."
              certbot certonly --standalone -d $DOMAIN --non-interactive --no-eff-email --agree-tos -m valentin@riten.dev
              if [ $? -ne 0 ]; then
                echo "Certbot failed! Check logs for details."
                exit 1
              fi
            else
              echo "Skipping renewal; Certbot will auto-renew via its systemd timer."
            fi
            
            # Set certificate permissions
            chmod 600 "$CERT_DIR/privkey.pem"
            chmod 644 "$CERT_DIR/fullchain.pem"
            
            # Stop existing service
            sudo killall -9 $SERVICE_NAME || true

            # Convert PEM files to PFX format
            echo "Converting PEM files to PFX format..."
            openssl pkcs12 -export \
              -inkey "$CERT_DIR/privkey.pem" \
              -in "$CERT_DIR/fullchain.pem" \
              -out "$PFX_CERT" \
              -password pass:$CERT_PASSWORD

            if [ $? -ne 0 ]; then
              echo "Failed to convert PEM to PFX!"
              exit 1
            fi

            # Debugging: Check generated PFX file
            ls -l "$PFX_CERT"

            # Delete the repository directory if it exists
            if [ -d "$REPO_DIR" ]; then
              echo "Deleting existing repository directory: $REPO_DIR"
              rm -rf $REPO_DIR
            fi
            
            # Clone the repository
            git config --global user.name "GitHub Actions"
            git config --global credential.helper store
            echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > ~/.git-credentials
            
            echo "Cloning the repository..."
            git clone --depth=1 https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $REPO_DIR
            cd $REPO_DIR
            
            # Build the project
            cd $SERVICE_NAME
            dotnet build --property:Configuration=Release
            
            # Start the application with HTTPS
            echo "Starting $SERVICE_NAME with HTTPS..."
            sudo nohup ./bin/Release/net8.0/$SERVICE_NAME \
              --url "$DOMAIN" \
              --cert "$PFX_CERT" \
              --secret "${{ secrets.COMM_SECRET }}" \
              --key "$CERT_PASSWORD" > /dev/null 2>&1 &
